baseurl = "https://www.otomore.com"
title = "otomore"
languageCode = "ja"
enableRobotsTXT = true
disableKinds=["RSS"]
googleAnalytics = "UA-123-45"
publishDir = "docs"

[blackfriday]
    hrefTargetBlank = true

[params]
  description = '<!--[-->otomore is an Developer based in Tokyo.<!--]--><br />
  <!--[-->It&rsquo;s a specification, not a bug.<!--]-->'
  logo = "fa-volume-up"
  copyright = "Otomore"
  Twitter = "@otomroe01"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/otomore01/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/yuto.nakano.545"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/otomore"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UCvsaWcIBIlN-xEa00gmJ_5g"
